linkage according graph

diff --git a/.github/actions/build_ya/action.yml b/.github/actions/build_ya/action.yml
--- a/.github/actions/build_ya/action.yml
+++ b/.github/actions/build_ya/action.yml
@@ -21,6 +21,10 @@ inputs:
     required: false
     default: "8"
     description: "link threads count"
+  do_link:
+    required: false
+    default: "false"
+    description: "Perform linkage or not (temporary transitional flaf)"
 outputs:
   success:
     value: ${{ steps.build.outputs.status }}
@@ -65,10 +69,12 @@ runs:
           extra_params+=(--bazel-remote-base-uri "${{ inputs.bazel_remote_uri }}")
         fi
         
+        remote_put_params=()
+
         if [ ! -z "${{ inputs.bazel_remote_username }}" ]; then
-          extra_params+=(--bazel-remote-username "${{ inputs.bazel_remote_username }}")
-          extra_params+=(--bazel-remote-password "${{ inputs.bazel_remote_password }}")
-          extra_params+=(--bazel-remote-put --dist-cache-evict-bins --add-result .o --add-result .a)
+          remote_put_params+=(--bazel-remote-username "${{ inputs.bazel_remote_username }}")
+          remote_put_params+=(--bazel-remote-password "${{ inputs.bazel_remote_password }}")
+          remote_put_params+=(--bazel-remote-put --dist-cache-evict-bins --add-result .o --add-result .a)
         fi
         
         case "${{ inputs.build_preset }}" in
@@ -115,14 +121,28 @@ runs:
         # to be sure
         set -o pipefail
         
+        # We don't want to put binaries (elf) to cache because its are too big, 
+        # so, if cache specified we do not perform linkage see '--dist-cache-evict-bins' flag
         ./ya make -k --build "${build_type}" --force-build-depends -T --stat -DCONSISTENT_DEBUG \
           --log-file "$TMP_DIR/ya_log.txt" --evlog-file "$TMP_DIR/ya_evlog.jsonl" \
           --cache-size 512G --link-threads "${{ inputs.link_threads }}" \
-          "${extra_params[@]}" |& tee $TMP_DIR/ya_make.log && echo "status=true" >> $GITHUB_OUTPUT || (
+          "${extra_params[@]}" "${remote_put_params[@]}" |& tee $TMP_DIR/ya_make.log && echo "status=true" >> $GITHUB_OUTPUT || (
               RC=$?
               echo "::debug::ya make RC=$RC"
               echo "status=failed" >> $GITHUB_OUTPUT
           )
+
+        if [ "${{ inputs.do_link }}" == "true" ]; then
+          # Perform linkage without "${remote_put_params[@]}"
+          ./ya make -k --build "${build_type}" --force-build-depends -T --stat -DCONSISTENT_DEBUG \
+            --log-file "$TMP_DIR/ya_log_linkage.txt" --evlog-file "$TMP_DIR/ya_evlog_linkage.jsonl" \
+            --cache-size 512G --link-threads "${{ inputs.link_threads }}" \
+            "${extra_params[@]}" |& tee $TMP_DIR/ya_make.log && echo "status=true" >> $GITHUB_OUTPUT || (
+                RC=$?
+                echo "::debug::ya make RC=$RC"
+                echo "status=failed" >> $GITHUB_OUTPUT
+            )
+        fi
 
     - name: sync logs to s3
       if: always()
