ci: cache tests results

diff --git a/.github/actions/test_ya/action.yml b/.github/actions/test_ya/action.yml
--- a/.github/actions/test_ya/action.yml
+++ b/.github/actions/test_ya/action.yml
@@ -41,9 +41,12 @@ inputs:
   bazel_remote_uri:
     required: false
     description: "bazel-remote endpoint"
-  cache_tests:
+  bazel_remote_username:
     required: false
-    description: "Use cache for tests"
+    description: "bazel-remote username"
+  bazel_remote_password:
+    required: false
+    description: "bazel-remote password"
 runs:
   using: "composite"
   steps:
@@ -78,7 +81,122 @@ runs:
     - name: Install Testmo CLI
       shell: bash
       run: npm install -g @testmo/testmo-cli
-    - name: Test history run create
+
+    - name: set environment variables required by some tests
+      shell: bash
+      run: |
+        echo "PSQL_BINARY=/usr/bin/psql" >> $GITHUB_ENV
+
+    - name: ya test
+      shell: bash
+      run: |
+        readarray -d ',' -t test_size < <(printf "%s" "${{ inputs.test_size }}")
+        readarray -d ',' -t test_type < <(printf "%s" "${{ inputs.test_type }}")
+
+        params=(
+          -T -k -D'BUILD_LANGUAGES=CPP PY3 PY2 GO'
+          ${test_size[@]/#/--test-size=} ${test_type[@]/#/--test-type=}
+          --cache-size 512G --do-not-output-stderrs
+          --stat --canonization-backend=ydb-canondata.storage.yandexcloud.net
+          --test-threads "${{ inputs.test_threads }}" --link-threads "${{ inputs.link_threads }}"
+        )
+        
+        # FIXME: copy-paste from build_ya
+        case "${{ inputs.build_preset }}" in
+          debug)
+            params+=(--build "debug")
+            ;;
+          relwithdebinfo)
+            params+=(--build "relwithdebinfo")
+            ;;
+          release-asan)
+            params+=(
+              --build "release" --sanitize="address"
+              -DSKIP_JUNK -DUSE_EAT_MY_DATA -DDEBUGINFO_LINES_ONLY
+            )
+            ;;
+          release-tsan)
+            params+=(
+              --build "release" --sanitize="thread"
+              -DSKIP_JUNK -DUSE_EAT_MY_DATA -DDEBUGINFO_LINES_ONLY
+            )
+            ;;
+          release-msan)
+            params+=(
+              --build "memory" --sanitize="thread"
+              -DSKIP_JUNK -DUSE_EAT_MY_DATA -DDEBUGINFO_LINES_ONLY
+            )
+            ;;
+          *)
+            echo "Invalid preset: ${{ inputs.build_preset }}"
+            exit 1
+            ;;
+        esac
+        
+        if [ ! -z "${{ inputs.build_target }}" ]; then
+          params+=(--target="${{ inputs.build_target }}")
+        fi
+
+        if [ ! -z "${{ inputs.bazel_remote_uri }}" ]; then
+          params+=(--bazel-remote-store)
+          params+=(--bazel-remote-base-uri "${{ inputs.bazel_remote_uri }}")
+        fi
+        
+        echo "::debug::get version"
+        ./ya --version
+        
+        if [ ! -z "${{ inputs.bazel_remote_username }}" ]; then
+          echo "::debug::start tests"
+
+          ./ya test "${params[@]}" \
+            --bazel-remote-put --bazel-remote-username "${{ inputs.bazel_remote_username }}" --bazel-remote-password "${{ inputs.bazel_remote_password }}" \
+            --log-file "$LOG_DIR/ya_log_prewarm.txt" --evlog-file "$LOG_DIR/ya_evlog_prewarm.jsonl" \
+            --dist-cache-evict-bins --cache-tests --no-dir-outputs --test-node-output-limit 100000 --drop-graph-result-before-tests
+        fi
+        
+        echo "::debug::save tests reports"
+        ./ya test "${params[@]}" \
+          --stat --log-file "$LOG_DIR/ya_log.txt" --evlog-file "$LOG_DIR/ya_evlog.jsonl" \
+          --cache-tests --dist-cache-evict-bins --no-dir-outputs --test-node-output-limit 100000 --drop-graph-result-before-tests \
+          --junit "$JUNIT_REPORT_XML" --output "$OUT_DIR" || (
+            RC=$?
+            if [ $RC -ne 0 ]; then
+              echo "ya test returned $RC, check existence $JUNIT_REPORT_XML"
+              if [ -s "$JUNIT_REPORT_XML" ]; then
+                echo "$JUNIT_REPORT_XML exists"
+                ls -la "$JUNIT_REPORT_XML"
+              else
+                echo "$JUNIT_REPORT_XML doesn't exist or has zero size"
+                ls -la "$JUNIT_REPORT_XML" || true
+                exit $RC
+              fi
+            fi
+        )
+
+    - name: archive unitest reports (orig)
+      shell: bash
+      run: |
+        gzip -c $JUNIT_REPORT_XML > $REPORTS_ARTIFACTS_DIR/orig_junit.xml.gz
+    
+    - name: postprocess junit report
+      shell: bash
+      run: |
+        .github/scripts/tests/transform-ya-junit.py -i \
+          --mu .github/config/muted_test.txt \
+          --mf .github/config/muted_functest.txt \
+          --ya-out "$OUT_DIR" \
+          --log-url-prefix "$S3_URL_PREFIX/logs/" \
+          --log-out-dir "$ARTIFACTS_DIR/logs/" \
+          "$JUNIT_REPORT_XML"
+    
+        .github/scripts/tests/split-junit.py -o "$JUNIT_REPORT_PARTS" "$JUNIT_REPORT_XML"
+    
+    - name: archive unitest reports (transformed)
+      shell: bash
+      run: |
+        tar -C $JUNIT_REPORT_PARTS/.. -czf $REPORTS_ARTIFACTS_DIR/junit_parts.xml.tar.gz $(basename $JUNIT_REPORT_PARTS)
+
+    - name: Upload tests result to testmo
       id: th
       if: inputs.testman_token
       shell: bash
@@ -135,117 +253,9 @@ runs:
         )
         echo "runid=${RUN_ID}" >> $GITHUB_OUTPUT
         echo "TEST_HISTORY_URL=${TESTMO_URL}/automation/runs/view/${RUN_ID}" >> $GITHUB_ENV
-
-    - name: Print test history link
-      shell: bash
-      run: |
-        echo "10 [Test history](${TEST_HISTORY_URL})" >> $SUMMARY_LINKS
-
-    - name: set environment variables required by some tests
-      shell: bash
-      run: |
-        echo "PSQL_BINARY=/usr/bin/psql" >> $GITHUB_ENV
-
-    - name: ya test
-      shell: bash
-      run: |
-        extra_params=()
         
-        # FIXME: copy-paste from build_ya
-        case "${{ inputs.build_preset }}" in
-          debug)
-            build_type=debug
-            ;;
-          relwithdebinfo)
-            build_type=relwithdebinfo
-            ;;
-          release-asan)
-            build_type=release
-            extra_params+=(--sanitize="address")
-            extra_params+=(-DSKIP_JUNK -DUSE_EAT_MY_DATA -DDEBUGINFO_LINES_ONLY)
-            ;;
-          release-tsan)
-            build_type=release
-            extra_params+=(--sanitize="thread")
-            extra_params+=(-DSKIP_JUNK -DUSE_EAT_MY_DATA -DDEBUGINFO_LINES_ONLY)
-            ;;
-          release-msan)
-            build_type=release
-            extra_params+=(--sanitize="memory")
-            extra_params+=(-DSKIP_JUNK -DUSE_EAT_MY_DATA -DDEBUGINFO_LINES_ONLY)
-            ;;
-          *)
-            echo "Invalid preset: ${{ inputs.build_preset }}"
-            exit 1
-            ;;
-        esac
-
-
-        if [ ! -z "${{ inputs.build_target }}" ]; then
-          extra_params+=(--target="${{ inputs.build_target }}")
-        fi
-
-        if [ ! -z "${{ inputs.bazel_remote_uri }}" ]; then
-          extra_params+=(--bazel-remote-store)
-          extra_params+=(--bazel-remote-base-uri "${{ inputs.bazel_remote_uri }}")
-        fi
-        
-        if [ "${{ inputs.cache_tests }}" = "true" ]; then
-          extra_params+=(--cache-tests)
-        fi
-        
-        readarray -d ',' -t test_size < <(printf "%s" "${{ inputs.test_size }}")
-        readarray -d ',' -t test_type < <(printf "%s" "${{ inputs.test_type }}")
-        
-        ./ya test -k --build "${build_type}" -D'BUILD_LANGUAGES=CPP PY3 PY2 GO' \
-          ${test_size[@]/#/--test-size=} ${test_type[@]/#/--test-type=} \
-          --test-threads "${{ inputs.test_threads }}" --link-threads "${{ inputs.link_threads }}" \
-          --cache-size 512G --do-not-output-stderrs -T \
-          --stat --log-file "$LOG_DIR/ya_log.txt" --evlog-file "$LOG_DIR/ya_evlog.jsonl" \
-          --canonization-backend=ydb-canondata.storage.yandexcloud.net \
-          --junit "$JUNIT_REPORT_XML" --output "$OUT_DIR" "${extra_params[@]}" || (
-            RC=$?
-            if [ $RC -ne 0 ]; then
-              echo "ya test returned $RC, check existence $JUNIT_REPORT_XML"
-              if [ -s "$JUNIT_REPORT_XML" ]; then
-                echo "$JUNIT_REPORT_XML exists"
-                ls -la "$JUNIT_REPORT_XML"
-              else
-                echo "$JUNIT_REPORT_XML doesn't exist or has zero size"
-                ls -la "$JUNIT_REPORT_XML" || true
-                exit $RC
-              fi
-            fi
-        )
-
-    - name: archive unitest reports (orig)
-      shell: bash
-      run: |
-        gzip -c $JUNIT_REPORT_XML > $REPORTS_ARTIFACTS_DIR/orig_junit.xml.gz
-    
-    - name: postprocess junit report
-      shell: bash
-      run: |
-        .github/scripts/tests/transform-ya-junit.py -i \
-          --mu .github/config/muted_test.txt \
-          --mf .github/config/muted_functest.txt \
-          --ya-out "$OUT_DIR" \
-          --log-url-prefix "$S3_URL_PREFIX/logs/" \
-          --log-out-dir "$ARTIFACTS_DIR/logs/" \
-          "$JUNIT_REPORT_XML"
-    
-        .github/scripts/tests/split-junit.py -o "$JUNIT_REPORT_PARTS" "$JUNIT_REPORT_XML"
-    
-    - name: archive unitest reports (transformed)
-      shell: bash
-      run: |
-        tar -C $JUNIT_REPORT_PARTS/.. -czf $REPORTS_ARTIFACTS_DIR/junit_parts.xml.tar.gz $(basename $JUNIT_REPORT_PARTS)
-
-    - name: Unit test history upload results
-      if: inputs.testman_token
-      shell: bash
-      run: |
         PROXY_ADDR=127.0.0.1:8888
+
         openssl req -x509 -newkey rsa:2048 \
           -keyout $TMP_DIR/key.pem -out $TMP_DIR/cert.pem \
           -sha256 -days 1 -nodes -subj "/CN=127.0.0.1"
@@ -260,10 +270,15 @@ runs:
         proxy_pid=$!
         
         NODE_TLS_REJECT_UNAUTHORIZED=0 testmo automation:run:submit-thread \
-          --instance "https://$PROXY_ADDR" --run-id ${{ steps.th.outputs.runid }} \
+          --instance "https://$PROXY_ADDR" --run-id "$RUN_ID" \
           --results "$JUNIT_REPORT_PARTS/*.xml"
         
         kill $proxy_pid
+
+    - name: Print test history link
+      shell: bash
+      run: |
+        echo "10 [Test history](${TEST_HISTORY_URL})" >> $SUMMARY_LINKS
 
     - name: Test history run complete
       if: always() && inputs.testman_token
