Remove build stage

diff --git a/.github/actions/test_ya/action.yml b/.github/actions/test_ya/action.yml
--- a/.github/actions/test_ya/action.yml
+++ b/.github/actions/test_ya/action.yml
@@ -36,9 +36,26 @@ inputs:
   testman_project_id:
     required: false
     description: "test manager project id"
+  put_build_results_to_cache:
+    required: false
+    default: "true"
   bazel_remote_uri:
     required: false
     description: "bazel-remote endpoint"
+  bazel_remote_username:
+    required: false
+    description: "bazel-remote username"
+  bazel_remote_password:
+    required: false
+    description: "bazel-remote password"
+  run_tests:
+    type: boolean
+    default: true
+    description: "run tests"
+outputs:
+  success:
+    value: ${{ steps.build.outputs.status }}
+    description: "build success"
 
 runs:
   using: "composite"
@@ -85,7 +102,7 @@ runs:
 
     - name: Upload tests result to testmo
       id: th
-      if: inputs.testman_token
+      if: inputs.testman_token && inputs.run_tests
       shell: bash
       env:
         PR_NUMBER: ${{ github.event.number }}
@@ -148,16 +165,18 @@ runs:
 
     - name: Print test history link
       shell: bash
-      if: inputs.testman_token
+      if: inputs.testman_token && inputs.run_test
       run: |
         echo "10 [Test history](${TEST_HISTORY_URL})" >> $SUMMARY_LINKS
 
     - name: set environment variables required by some tests
+      if: inputs.run_test
       shell: bash
       run: |
         echo "PSQL_BINARY=/usr/bin/psql" >> $GITHUB_ENV
 
-    - name: ya test
+    - name: ya build and test
+      id: build
       shell: bash
       run: |
         set -x
@@ -172,7 +191,6 @@ runs:
           --test-threads "${{ inputs.test_threads }}" --link-threads "${{ inputs.link_threads }}"
         )
         
-        # FIXME: copy-paste from build_ya
         case "$BUILD_PRESET" in
           debug)
             params+=(--build "debug")
@@ -213,37 +231,41 @@ runs:
           params+=(--bazel-remote-base-uri "${{ inputs.bazel_remote_uri }}")
         fi
 
+        if [ true = ${{ inputs.run_tests }} ]; then
+          params+=(-A)
+        fi
+
+
         echo "::debug::get version"
         ./ya --version
         
-        echo "Tests are running..." | GITHUB_TOKEN="${{ github.token }}" .github/scripts/tests/comment-pr.py
+        echo "Build+tests are running..." | GITHUB_TOKEN="${{ github.token }}" .github/scripts/tests/comment-pr.py
         
-        ./ya test ${{ inputs.build_target }} "${params[@]}" \
+        ./ya make ${{ inputs.build_target }} "${params[@]}" \
           --stat --log-file "$YA_TEST_LOG_FILENAME" -DCONSISTENT_DEBUG \
-          --no-dir-outputs \
+          --no-dir-outputs --test-failure-code 0 \
+          --cache-size 2TB --force-build-depends --evlog-file "$TMP_DIR/ya_evlog.jsonl" \
           --junit "$JUNIT_REPORT_XML" --output "$OUT_DIR" || (
             RC=$?
             if [ $RC -ne 0 ]; then
               echo "10 [Test run log]($YA_TEST_LOG_URL)" >> $SUMMARY_LINKS
 
-              echo "ya test returned $RC, check existence $JUNIT_REPORT_XML"
-              if [ -s "$JUNIT_REPORT_XML" ]; then
-                echo "$JUNIT_REPORT_XML exists"
-                ls -la "$JUNIT_REPORT_XML"
-              else
-                echo "$JUNIT_REPORT_XML doesn't exist or has zero size"
-                ls -la "$JUNIT_REPORT_XML" || true
-                exit $RC
-              fi
+              echo "ya make returned $RC, build failed"
+              echo "status=failed" >> $GITHUB_OUTPUT
+              exit $RC
+            else
+              echo "status=true" >> $GITHUB_OUTPUT
             fi
         )
 
     - name: archive unitest reports (orig)
+      if: inputs.run_test
       shell: bash
       run: |
         gzip -c $JUNIT_REPORT_XML > $REPORTS_ARTIFACTS_DIR/orig_junit.xml.gz
 
     - name: postprocess junit report
+      if: inputs.run_test
       shell: bash
       run: |
         set -x
@@ -259,7 +281,7 @@ runs:
         .github/scripts/tests/split-junit.py -o "$JUNIT_REPORT_PARTS" "$JUNIT_REPORT_XML"
     
     - name: Test history upload results to YDB
-      if: always()
+      if: inputs.run_test
       continue-on-error: true
       shell: bash
       env:
@@ -281,12 +303,13 @@ runs:
         result=`.github/scripts/upload_tests_results.py --test-results-file ${JUNIT_REPORT_XML} --run-timestamp $(date +%s) --commit $(git rev-parse HEAD) --build-type ${BUILD_PRESET} --pull ${PR_NUMBER} --job-name ${JOB_NAME} --job-id ${JOB_ID} --branch ${GITHUB_REF_NAME}`
 
     - name: archive unitest reports (transformed)
+      if: inputs.run_test
       shell: bash
       run: |
         tar -C $JUNIT_REPORT_PARTS/.. -czf $REPORTS_ARTIFACTS_DIR/junit_parts.xml.tar.gz $(basename $JUNIT_REPORT_PARTS)
 
     - name: Unit test history upload results
-      if: inputs.testman_token
+      if: inputs.testman_token && inputs.run_test
       shell: bash
       env:
         TESTMO_TOKEN: ${{ inputs.testman_token }}
@@ -314,7 +337,7 @@ runs:
         kill $proxy_pid
 
     - name: Test history run complete
-      if: always() && inputs.testman_token
+      if: always() && inputs.testman_token && inputs.run_test
       shell: bash
       env:
         TESTMO_TOKEN: ${{ inputs.testman_token }}
@@ -332,7 +355,7 @@ runs:
     
     - name: write tests summary
       shell: bash
-      if: always()
+      if: always() && inputs.run_test
       env:
         GITHUB_TOKEN: ${{ github.token }}
       run: |
@@ -361,7 +384,7 @@ runs:
             -d '{"state":"'$teststatus'","description":"'"$testmessage"'","context":"test_${{inputs.build_preset}}"}'
 
     - name: sync test results to s3
-      if: always()
+      if: always() && inputs.run_test
       shell: bash
       run: |
         set -x
@@ -371,6 +394,7 @@ runs:
         echo "::endgroup::"
     
     - name: check test results
+      if: inputs.run_test
       shell: bash
       run: |
         .github/scripts/tests/fail-checker.py "$JUNIT_REPORT_XML"
