Failed tests threshhold

diff --git a/.github/actions/test_ya/action.yml b/.github/actions/test_ya/action.yml
--- a/.github/actions/test_ya/action.yml
+++ b/.github/actions/test_ya/action.yml
@@ -87,7 +87,7 @@ runs:
         echo "PUBLIC_DIR_URL=$PUBLIC_DIR_URL" >> $GITHUB_ENV
         mkdir -p $PUBLIC_DIR
 
-        echo "JUNIT_REPORT_XML=$PUBLIC_DIR/junit.xml" >> $GITHUB_ENV
+        echo "LAST_JUNIT_REPORT_XML=$PUBLIC_DIR/last_junit.xml" >> $GITHUB_ENV
         echo "TESTMO_URL=${{ inputs.testman_url }}" >> $GITHUB_ENV
         echo "SUMMARY_LINKS=$PUBLIC_DIR/summary_links.txt" >> $GITHUB_ENV
         echo "BUILD_PRESET=${{ inputs.build_preset }}" >> $GITHUB_ENV
@@ -335,7 +335,7 @@ runs:
             --log_out_dir "$CURRENT_PUBLIC_DIR_RELATIVE/artifacts/logs/" \
             --test_stuff_out "$CURRENT_PUBLIC_DIR_RELATIVE/test_artifacts/" \
             "$CURRENT_JUNIT_XML_PATH"
-          cp $CURRENT_JUNIT_XML_PATH $JUNIT_REPORT_XML
+          cp $CURRENT_JUNIT_XML_PATH $LAST_JUNIT_REPORT_XML
 
           if [ "${{ inputs.run_tests }}" = "true" ]; then
             GITHUB_TOKEN=${{ github.token }} .github/scripts/tests/generate-summary.py \
@@ -359,7 +359,7 @@ runs:
             # split large junit_report
             export TESTMO_JUNIT_REPORT_PARTS=$TMP_DIR/junit-split
             mkdir -p $TESTMO_JUNIT_REPORT_PARTS
-            .github/scripts/tests/split-junit.py -o "$TESTMO_JUNIT_REPORT_PARTS" "$JUNIT_REPORT_XML"
+            .github/scripts/tests/split-junit.py -o "$TESTMO_JUNIT_REPORT_PARTS" "$CURRENT_JUNIT_XML_PATH"
             # archive unitest reports (transformed)
             tar -C $TESTMO_JUNIT_REPORT_PARTS/.. -czf $PUBLIC_DIR/junit_parts.xml.tar.gz $(basename $TESTMO_JUNIT_REPORT_PARTS)
 
@@ -389,7 +389,14 @@ runs:
           fi
 
           TESTS_RESULT=0
-          .github/scripts/tests/fail-checker.py "$CURRENT_JUNIT_XML_PATH" || TESTS_RESULT=$?
+          .github/scripts/tests/fail-checker.py "$CURRENT_JUNIT_XML_PATH" --output_path $CURRENT_PUBLIC_DIR/failed_count.txt || TESTS_RESULT=$?
+
+          FAILED_TESTS_COUNT=$(cat $CURRENT_PUBLIC_DIR/failed_count.txt)
+
+          if [ $FAILED_TESTS_COUNT -gt 500 ]; then 
+            TOO_MANY_FAILED="Too many tests failed, NOT going to retry"
+            echo $TOO_MANY_FAILED | GITHUB_TOKEN="${{ github.token }}" .github/scripts/tests/comment-pr.py --fail
+          fi
 
           if [ $TESTS_RESULT = 0 ]; then
             break
@@ -455,7 +462,7 @@ runs:
       if: inputs.run_tests
       shell: bash
       run: |
-        .github/scripts/tests/fail-checker.py "$JUNIT_REPORT_XML"
+        .github/scripts/tests/fail-checker.py "$LAST_JUNIT_REPORT_XML"
 
     - name: sync results to s3 and publish links
       if: always()
