Local YDB: add custom init scripts support for YDB Docker container (#28811)
Signed-off-by: Vladislav Polyakov <polRk@ydb.tech>
Signed-off-by: Vladislav Polyakov <polrk@ydb.tech>

diff --git a/.github/docker/Dockerfile b/.github/docker/Dockerfile
--- a/.github/docker/Dockerfile
+++ b/.github/docker/Dockerfile
@@ -8,20 +8,34 @@ RUN apt-get update \
     && apt-get install -y --no-install-recommends \
       python3 curl lsb-release python3-dev libc6-dev libidn11-dev libaio1 libaio-dev libgcc-11-dev binutils tree git
 
-COPY ydb/ /ydbwork/ydb/
-
-WORKDIR /ydbwork/ydb/
-
+COPY ydbd/ /ydbwork/ydbd/
+WORKDIR /ydbwork/ydbd/
 RUN ./ya make -r -T \
       -C ydb/apps/ydbd/ydbd \
-      -C ydb/apps/ydb/ydb \
-      -C ydb/public/tools/local_ydb/local_ydb \
       -o /ydbwork/out/ \
     && /ydbwork/out/ydb/apps/ydbd/ydbd -V \
     && tree /ydbwork/out/ \
-    && strip /ydbwork/out/ydb/apps/ydbd/ydbd /ydbwork/out/ydb/apps/ydb/ydb /ydbwork/out/ydb/public/tools/local_ydb/local_ydb \
+    && strip /ydbwork/out/ydb/apps/ydbd/ydbd \
     && rm -rf ~/.ya  || echo 'unable to delete ~/.ya' # for reduce cache size
 
+COPY cli/ /ydbwork/cli/
+WORKDIR /ydbwork/cli/
+RUN ./ya make -r -T \
+      -C ydb/apps/ydb/ydb \
+      -o /ydbwork/out/ \
+    && /ydbwork/out/cli/apps/ydb/ydb version \
+    && tree /ydbwork/out/ \
+    && strip /ydbwork/out/ydb/apps/ydb/ydb \
+    && rm -rf ~/.ya  || echo 'unable to delete ~/.ya' # for reduce cache size
+
+COPY local_ydb/ /ydbwork/local_ydb/
+WORKDIR /ydbwork/local_ydb/
+RUN ./ya make -r -T \
+      -C ydb/public/tools/local_ydb/local_ydb \
+      -o /ydbwork/out/ \
+    && tree /ydbwork/out/ \
+    && strip /ydbwork/out/ydb/public/tools/local_ydb/local_ydb \
+    && rm -rf ~/.ya  || echo 'unable to delete ~/.ya' # for reduce cache size
 
 FROM ubuntu:22.04
 RUN apt-get update  \
@@ -30,8 +44,8 @@ RUN apt-get update  \
 
 RUN mkdir -p /root/ydb/bin/ \
     && mkdir -p /ydb_data \
-    && mkdir -p /ydb_certs \
-    && /ydbwork/out/ydb/apps/ydb/ydb version --disable-checks
+    && mkdir -p ydb_certs \
+    && echo '{"check_version":false}' > root/ydb/bin/config.json
 
 COPY main/.github/docker/files/ /
 COPY --from=builder \
@@ -48,4 +62,4 @@ EXPOSE ${YDB_KAFKA_PROXY_PORT:-9092}
 
 HEALTHCHECK --start-period=60s --interval=60s CMD sh /health_check
 
-ENTRYPOINT ["bash", "/initialize_local_ydb"]
+CMD ["bash", "/initialize_local_ydb"]
