hr_comment

diff --git a/.github/actions/build_and_test_ya/action.yml b/.github/actions/build_and_test_ya/action.yml
--- a/.github/actions/build_and_test_ya/action.yml
+++ b/.github/actions/build_and_test_ya/action.yml
@@ -117,6 +117,45 @@ runs:
         put_build_results_to_cache: ${{ inputs.put_build_results_to_cache }}
         link_threads: ${{ inputs.link_threads }}
         additional_ya_make_args: ${{ inputs.additional_ya_make_args }}
+
+    - name: Run tests
+      uses: ./.github/actions/test_ya
+      if: ${{ inputs.run_tests == 'true' &&  (steps.build.outputs.success == 'true' || inputs.run_tests_if_build_fails == 'true') }}
+      with:
+        build_target: ${{ steps.test_run_choice.outputs.target }}
+        build_preset: ${{ inputs.build_preset }}
+        test_size: ${{ inputs.test_size }}
+        test_type: ${{ inputs.test_type }}
+        testman_token: ${{ fromJSON( inputs.secs ).TESTMO_TOKEN }}
+        testman_url: ${{  fromJSON( inputs.vars ).TESTMO_URL }}
+        testman_project_id: ${{  fromJSON( inputs.vars ).TESTMO_PROJECT_ID }}
+        link_threads: ${{ inputs.link_threads }}
+        additional_ya_make_args: ${{ inputs.additional_ya_make_args }}
+        test_threads: ${{ inputs.test_threads }}
+
+    
+    - name: Notify about failed build
+      if: ${{ steps.build.outputs.success != 'true' && inputs.run_tests == 'true' && inputs.run_tests_if_build_fails == 'false' }}
+      shell: bash
+      run: |
+        echo 'Build failed. See the [build log](${{ steps.build.outputs.log_url }}).' >> $GITHUB_STEP_SUMMARY
+        
+        if [[ "$GITHUB_EVENT_NAME" =~ ^pull_request ]]; then
+          echo "Tests run skipped." | .github/scripts/tests/comment-pr.py --fail
+        fi
+        
+        exit 1
+        
+    - name: build_stats
+      shell: bash
+      continue-on-error: true
+      if: always()
+      run: |
+        set -x
+        export build_preset="${{ inputs.build_preset }}" 
+        python3 -m pip install ydb ydb[yc]
+        python3 .github/scripts/send_build_stats.py
+
     - name: show_build_size_diff
       shell: bash
       continue-on-error: true
@@ -162,55 +201,18 @@ runs:
 
           bytes_diff=$((main_size_bytes-current_size_bytes))
           main_url="https://github.com/ydb-platform/ydb/commit/"$main_github_sha
-          human_readable_size=bytesToHumanIEC $current_size_bytes
+
+          human_readable_size=`bytesToHumanIEC $current_size_bytes`
+          human_readable_size_diff=`bytesToHumanIEC bytes_diff`
           if [ "0" -ge "$bytes_diff" ]; then
-            echo "Current build [$current_size_bytes](https://datalens.yandex/cu6hzmpaki700):+$bytes_diff bytes than [main:${main_github_sha:0:8}]($main_url)" | .github/scripts/tests/comment-pr.py --color green
+            echo "Current build [$current_size_bytes](https://datalens.yandex/cu6hzmpaki700):+$human_readable_size_diff than [main:${main_github_sha:0:8}]($main_url)" | .github/scripts/tests/comment-pr.py --color red
           else
-            echo "Current build [$current_size_bytes](https://datalens.yandex/cu6hzmpaki700):$bytes_diff bytes than [main:${main_github_sha:0:8}]($main_url)" | .github/scripts/tests/comment-pr.py --color red
+            echo "Current build [$current_size_bytes](https://datalens.yandex/cu6hzmpaki700):$human_readable_size_diff than [main:${main_github_sha:0:8}]($main_url)" | .github/scripts/tests/comment-pr.py --color green
           fi
         else
           echo "Skipped build size difference"
         fi
 
-    - name: Run tests
-      uses: ./.github/actions/test_ya
-      if: ${{ inputs.run_tests == 'true' &&  (steps.build.outputs.success == 'true' || inputs.run_tests_if_build_fails == 'true') }}
-      with:
-        build_target: ${{ steps.test_run_choice.outputs.target }}
-        build_preset: ${{ inputs.build_preset }}
-        test_size: ${{ inputs.test_size }}
-        test_type: ${{ inputs.test_type }}
-        testman_token: ${{ fromJSON( inputs.secs ).TESTMO_TOKEN }}
-        testman_url: ${{  fromJSON( inputs.vars ).TESTMO_URL }}
-        testman_project_id: ${{  fromJSON( inputs.vars ).TESTMO_PROJECT_ID }}
-        link_threads: ${{ inputs.link_threads }}
-        additional_ya_make_args: ${{ inputs.additional_ya_make_args }}
-        test_threads: ${{ inputs.test_threads }}
-
-    
-    - name: Notify about failed build
-      if: ${{ steps.build.outputs.success != 'true' && inputs.run_tests == 'true' && inputs.run_tests_if_build_fails == 'false' }}
-      shell: bash
-      run: |
-        echo 'Build failed. See the [build log](${{ steps.build.outputs.log_url }}).' >> $GITHUB_STEP_SUMMARY
-        
-        if [[ "$GITHUB_EVENT_NAME" =~ ^pull_request ]]; then
-          echo "Tests run skipped." | .github/scripts/tests/comment-pr.py --fail
-        fi
-        
-        exit 1
-        
-    - name: build_stats
-      shell: bash
-      continue-on-error: true
-      if: always()
-      run: |
-        set -x
-        export build_preset="${{ inputs.build_preset }}" 
-        python3 -m pip install ydb ydb[yc]
-        python3 .github/scripts/send_build_stats.py
-
-    
     - name: comment-if-cancel
       shell: bash
       if: cancelled() && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
